# web1-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web1
        image: baong7724/web1:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web1-service
spec:
  selector:
    app: web1
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
