# web2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: baong7724/web2:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web2-service
spec:
  selector:
    app: web2
  type: ClusterIP  
  ports:
    - port: 80
      targetPort: 80
