apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-static-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-static
  template:
    metadata:
      labels:
        app: web-static
    spec:
      containers:
      - name: web-static
        image: baong7724/web-static:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-static-service
spec:
  type: NodePort
  selector:
    app: web-static
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008  
